---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: -----/backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: pg_url
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: REPORT_PATH
              value: "/app/logs"
            - name: LOG_PATH
              value: "/app"
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: host
            - name: SPRING_CLOUD_VAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: port
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: token
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1025Mi
              cpu: 4000m
      imagePullSecrets:
        - name: regcreds
