---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcreds
  labels:
    app: backend
data:
  .dockerconfigjson: |-
    -----

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault
  labels:
    app: backend
data:
  token: -----
  host: -----
  port: -----

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend
  labels:
    app: backend
data:
  pg_url: |-
    ----
