---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      app.kubernetes.io/managed-by: "{{ .Release.Service }}"
      helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      app.kubernetes.io/component: {{ .Chart.Name }}
      app.kubernetes.io/part-of: {{ .Values.global.project }}
      env: "{{ .Values.global.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repo }}{{ .Values.image }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            {{- range $name, $value := .Values.envSecrets }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret }}
                  key: {{ $value.key }}
            {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
      {{- range $name := .Values.global.imagePullSecrets }}
        - name: {{ $name }}
      {{- end }}
