---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.nginx.configMapName }}
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |
    server {    
      listen {{ .Values.service.port }};
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }
      location /api {
        proxy_pass {{ .Values.service.nginx.backendUrl }};
      }
    }
