---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.portExt }}
      protocol: TCP
      name: {{ .Chart.Name }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
