---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      name: backend-report
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: -----/backend-report:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: host
            - name: SPRING_CLOUD_VAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: port
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: token
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1025Mi
              cpu: 200m
      imagePullSecrets:
        - name: regcreds
