---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcreds
  labels:
    app: {{ .Chart.Name }}
data:
  .dockerconfigjson: {{ .Values.global.regcreds }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vault
  labels:
    app: {{ .Chart.Name }}
data:
  token: {{ .Values.global.vault.token | b64enc }}
  host: {{ .Values.global.vault.host | b64enc }}
  port: {{ .Values.global.vault.port | b64enc }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend
  labels:
    app: {{ .Chart.Name }}
data:
  pg_url: {{ .Values.global.pg_url | b64enc }}
